name: Basic Directory Creation Job

on:
  push:
    branches:
      - main # Adjust branch as needed

jobs:
  create-directory:
    runs-on: self-hosted

    steps:
      - name: Create Directory
        run: mkdir -p /mnt/ajay
