name: Clone Repository and Create Project Directory

on:
  push:
    branches:
      - main # Adjust branch as needed

jobs:
  clone-repo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Alternatively, you can run 'git clone' directly

      - name: Clone repository to /mnt
        run: |
          sudo rm -rf /mnt/project
          sudo mkdir -p /mnt/project
          cd /mnt/project
          sudo git clone https://github.com/doijadajay/game-of-life.git .
          # Replace the URL with your repository URL

      - name: Build with Maven
        working-directory: /mnt/project
        run: sudo mvn clean install


      - name: List cloned directory
        run: ls -l /mnt/project # List the cloned directory to verify it's been cloned
