name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Game of Life repository
        run: sudo git clone https://github.com/doijadajay/game-of-life.git
        # Replace 'your-username' with your actual GitHub username

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: |
          cd game-of-life  # Move into the cloned directory
          mvn clean install
