name: Clone and Maven Build

on:
  push:
    branches:
      - main  # Adjust branch name if needed
  pull_request:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create project directory
        run: mkdir project

      - name: Change to project directory
        run: cd project

      - name: Clone repository
        run: git clone https://github.com/doijadajay/game-of-life.git

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'  # Use Java 8

      - name: Build with Maven (clean and skip tests)
        run: |
          cd game-of-life  # Change directory to the cloned repository
          mvn -B clean package -DskipTests
